### ISSUE TITLE
Question about avgpool size in backbone.py

### ISSUE THREAD

**Issue by huangxilang901** [megvii-research/DPGN#13]
Thanks for your sharing. 
I encountered a problem about the size of avgpool.
When I implement your code, I found that the size of input before avgpool is 512X6X6  for miniimagenet dataset. However, since the filter size of avgpool is 7X7, the output size is too small (i.e., 512X0X0).
Could you help me solve the problem?
Thank you.

**Comment by zilunzhang** [comment]
Hi xilang,

We didn't encounter this problem in any combination of datasets and backbones in our enviroment. Have you tried the enviroment we listed?

Best,

DPGN team

**Comment by zilunzhang** [comment]
> Thanks for your sharing.
> I encountered a problem about the size of avgpool.
> When I implement your code, I found that the size of input before avgpool is 512X6X6 for miniimagenet dataset. However, since the filter size of avgpool is 7X7, the output size is too small (i.e., 512X0X0).
> Could you help me solve the problem?
> Thank you.

Hi xilang,

We didn't encounter this problem in any combination of datasets and backbones in our enviroment. Have you tried the enviroment we listed?

Best,

DPGN team

**Comment by huangxilang901** [comment]
> > Thanks for your sharing.
> > I encountered a problem about the size of avgpool.
> > When I implement your code, I found that the size of input before avgpool is 512X6X6 for miniimagenet dataset. However, since the filter size of avgpool is 7X7, the output size is too small (i.e., 512X0X0).
> > Could you help me solve the problem?
> > Thank you.
> 
> Hi xilang,
> 
> We didn't encounter this problem in any combination of datasets and backbones in our enviroment. Have you tried the enviroment we listed?
> 
> Best,
> 
> DPGN team

Thank you for your reply!
I did not run the code in ubuntu, but implemented it in Windows 10. Is it anything to do with the os? Because i believe that the version of package should not have any affect on the size of output images...

Thank you!

**Comment by zilunzhang** [comment]
> > > Thanks for your sharing.
> > > I encountered a problem about the size of avgpool.
> > > When I implement your code, I found that the size of input before avgpool is 512X6X6 for miniimagenet dataset. However, since the filter size of avgpool is 7X7, the output size is too small (i.e., 512X0X0).
> > > Could you help me solve the problem?
> > > Thank you.
> > 
> > 
> > Hi xilang,
> > We didn't encounter this problem in any combination of datasets and backbones in our enviroment. Have you tried the enviroment we listed?
> > Best,
> > DPGN team
> 
> Thank you for your reply!
> I did not run the code in ubuntu, but implemented it in Windows 10. Is it anything to do with the os? Because i believe that the version of package should not have any affect on the size of output images...
> 
> Thank you!

Hi xilang,

I think it could be. For example, if the default value of padding number or some other default value of parameters that related to the output size of convolution operations are changed in different versions of PyTorch. 

Best,

DPGN teams
