### ISSUE TITLE
Reproduce issues on Cifar-fs and TieredImagenet

### ISSUE THREAD

**Issue by tangshixiang** [megvii-research/DPGN#2]
Dear Yang:

Thank you for releasing the repo. Could you share the detailed learning schedule for Cifar-fs and TieredImagenet datasets for reproducing the results reported in the paper?

Best,
TANG, shixiang

**Comment by zilunzhang** [comment]
Hi Shixiang,

Thanks for the suggestion. Config files of CIFAR-FS, CUB-200-2011, and Tiered-ImageNet has been uploaded.

The differences between model complexity of backbones require various training strategies. Type of losses, coefficients, optimizer parameters, and learning schedule could be different in this case. What's more, different scales of datasets may need different training strategies as well (underfit/overfit issue, etc.).

Let us know if you have any other confusion when reproducing the DPGN.

Best,

DPGN Team

**Comment by zilunzhang** [comment]
> Dear Yang:
> 
> Thank you for releasing the repo. Could you share the detailed learning schedule for Cifar-fs and TieredImagenet datasets for reproducing the results reported in the paper?
> 
> Best,
> TANG, shixiang

**Comment by zilunzhang** [comment]
> Dear Yang:
> 
> Thank you for releasing the repo. Could you share the detailed learning schedule for Cifar-fs and TieredImagenet datasets for reproducing the results reported in the paper?
> 
> Best,
> TANG, shixiang

Hi Shixiang,

Thanks for the suggestion. Config files of CIFAR-FS, CUB-200-2011, and Tiered-ImageNet has been uploaded.

The differences between model complexity of backbones require various training strategies. Type of losses, coefficients, optimizer parameters, and learning schedule could be different in this case. What's more, different scales of datasets may need different training strategies as well (underfit/overfit issue, etc.).

Let us know if you have any other confusion when reproducing the DPGN.

Best,

DPGN Team
