### ISSUE TITLE
How to  make  Dataset？

### ISSUE THREAD

**Issue by Zhong-shan** [megvii-research/DPGN#3]
Dear Yang,

Thank you for releasing the repo. Could you give me detailed instructions on how to make the data set in the paper?

Best,
Zhongshan Bao

**Comment by zilunzhang** [comment]
Hi Zhongshan,

Thanks for being interested in our work. Please refer to README file for detail (It has been updated).

Let us know if you have any other confusion when reproducing the DPGN.

Best,

DPGN Team

**Comment by zilunzhang** [comment]
> Hi Zhongshan,
> 
> Thanks for being interested in our work. Please refer to README file for detail (It has been updated).
> 
> Let us know if you have any other confusion when reproducing the DPGN.
> 
> Best,
> 
> DPGN Team

Hi Zhongshan,

Thanks for being interested in our work. Please refer to README file for detail (It has been updated).

Let us know if you have any other confusion when reproducing the DPGN.

Best,

DPGN Team

**Comment by Zhong-shan** [comment]
> 
> 
> > Dear Yang,
> > Thank you for releasing the repo. Could you give me detailed instructions on how to make the data set in the paper?
> > Best,
> > Zhongshan Bao
> 
> Hi Zhongshan,
> 
> Thanks for being interested in our work. Please refer to README file for detail (It has been updated).
> 
> Let us know if you have any other confusion when reproducing the DPGN.
> 
> Best,
> 
> DPGN Team

OK, I will try it. Thank you.
