### ISSUE TITLE
性能和论文中不符

### ISSUE THREAD

**Issue by jocelynhhh** [megvii-research/DPGN#33]
在为miniImageNet分类中使用DPGN backbone为convNet 5way5shot的情况下准确率与文中相应情况的准确率差别有5%。请问是为什么呢？

**Comment by zilunzhang** [comment]
请参考问题 #1

**Comment by jocelynhhh** [comment]
您好，感谢回复，这个参数我看了是和代码中的参数文件是一致的，我并没有修改，但是仍然无法得到论文中的结果。
| |
赖鸣姝
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Zilun ***@***.***> |
| 发送日期 | 2022年7月1日 11:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [megvii-research/DPGN] 性能和论文中不符 (Issue #33) |

请参考问题 #1
