### ISSUE TITLE
can't find pretrained model

### ISSUE THREAD

**Issue by xjd-ziyu** [megvii-research/DPGN#4]
Dear yang,
I want to ask for help. When I open the google drive to download the pretrained model mentioned in README.md. there is nothing in that folder.  I don't know what to do. Could you share it with me again? 
Thank you! Looking forward to your reply.

**Comment by zilunzhang** [comment]
> Dear yang,
> I want to ask for help. When I open the google drive to download the pretrained model mentioned in README.md. there is nothing in that folder. I don't know what to do. Could you share it with me again?
> Thank you! Looking forward to your reply.

Hi Ziyu,

We appreciate your interest in our work.

I accidentally deleted the checkpoints when I cleaned my google drive (almost full) on May 7th. The checkpoints have been reuploaded, please check.

Best,

DPGN team.
