### ISSUE TITLE
Can you release the config file of Conv4 in miniImageNet and CIFAR_FS?

### ISSUE THREAD

**Issue by WHQ1111** [megvii-research/DPGN#6]
I want to reproduce you result,  and I believe different configurations have big impact on the final result. So can you release the config file of Conv4 in miniImageNet and CIFAR_FS? Thank you very much.

**Comment by zilunzhang** [comment]
Hi,

We are organizing the config files you asked. It should be released soon.

For config file of convnet + mini-imagenet + 5way-5shot, please refer to issue #1 

Best,

DPGN team
